name: Sync to Gitee
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */6 * * *' # 每6小时同步一次
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_TOKEN }}
        with:
          source-repo: "https://github.com/guangwen1648/LibreTV.git"
          destination-repo: "https://gitee.com/guangwenchen/LibreTV.git"
